/* Generated By:JavaCC: Do not edit this line. FortranParserTokenManager.java */
package Command.JavaCC.Fortran;
import java.io.StringReader;
import java.util.*;

public class FortranParserTokenManager implements FortranParserConstants
{
  public static  java.io.PrintStream debugStream = System.out;
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 59:
         return jjStopAtPos(0, 32);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
static private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
static private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
static private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 338;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(233, 234);
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 5)
                        kind = 5;
                     jjCheckNAdd(0);
                  }
                  else if (curChar == 46)
                     jjCheckNAdd(22);
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 11);
                  break;
               case 0:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 45)
                     jjCheckNAddStates(12, 18);
                  break;
               case 3:
                  if ((0xfc00fffaffffd9ffL & l) != 0L)
                     jjCheckNAddStates(12, 18);
                  break;
               case 4:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(12, 18);
                  break;
               case 5:
                  if (curChar == 46)
                     jjCheckNAdd(6);
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(19, 26);
                  break;
               case 8:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 33);
                  break;
               case 10:
                  if (curChar != 34)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAdd(10);
                  break;
               case 11:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(34, 36);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(12, 18);
                  break;
               case 13:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(12, 14);
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(37, 44);
                  break;
               case 15:
                  if (curChar == 46)
                     jjCheckNAddStates(45, 53);
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(54, 65);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(66, 76);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(77, 89);
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(90, 101);
                  break;
               case 20:
                  if (curChar != 34)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjCheckNAddStates(102, 109);
                  break;
               case 21:
                  if (curChar == 46)
                     jjCheckNAdd(22);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(22, 23);
                  break;
               case 24:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(24, 25);
                  break;
               case 26:
                  if (curChar == 40)
                     jjCheckNAddStates(110, 114);
                  break;
               case 27:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(110, 114);
                  break;
               case 28:
                  if (curChar == 46)
                     jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(115, 121);
                  break;
               case 31:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(32);
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(122, 127);
                  break;
               case 33:
                  if (curChar == 45)
                     jjCheckNAddStates(128, 133);
                  break;
               case 34:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 35:
                  if (curChar == 41 && kind > 21)
                     kind = 21;
                  break;
               case 36:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(37, 41);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(134, 140);
                  break;
               case 38:
                  if (curChar == 46)
                     jjCheckNAddStates(141, 148);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(149, 159);
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(160, 169);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(128, 133);
                  break;
               case 42:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(170, 172);
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(173, 184);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(185, 195);
                  break;
               case 48:
                  if (curChar == 40)
                     jjCheckNAddStates(196, 200);
                  break;
               case 49:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(196, 200);
                  break;
               case 50:
                  if (curChar == 46)
                     jjCheckNAdd(51);
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(201, 207);
                  break;
               case 53:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(54);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(208, 213);
                  break;
               case 55:
                  if (curChar == 45)
                     jjCheckNAddStates(214, 219);
                  break;
               case 56:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 57:
                  if (curChar == 41 && kind > 22)
                     kind = 22;
                  break;
               case 58:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(59, 63);
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(220, 226);
                  break;
               case 60:
                  if (curChar == 46)
                     jjCheckNAddStates(227, 234);
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(235, 245);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(246, 255);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(214, 219);
                  break;
               case 64:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(256, 258);
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(259, 270);
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(271, 281);
                  break;
               case 71:
                  if (curChar == 40)
                     jjCheckNAddStates(282, 285);
                  break;
               case 72:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(282, 285);
                  break;
               case 73:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(286, 290);
                  break;
               case 75:
                  if (curChar == 45)
                     jjCheckNAddStates(286, 290);
                  break;
               case 76:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(76, 77);
                  break;
               case 77:
                  if (curChar == 41 && kind > 23)
                     kind = 23;
                  break;
               case 83:
                  if (curChar == 40)
                     jjCheckNAddStates(291, 294);
                  break;
               case 84:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(291, 294);
                  break;
               case 85:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(86);
                  break;
               case 86:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(295, 299);
                  break;
               case 87:
                  if (curChar == 45)
                     jjCheckNAddStates(295, 299);
                  break;
               case 88:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(88, 89);
                  break;
               case 89:
                  if (curChar == 41 && kind > 25)
                     kind = 25;
                  break;
               case 94:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(300, 310);
                  break;
               case 95:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(96);
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(311, 316);
                  break;
               case 97:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(311, 316);
                  break;
               case 98:
                  if (curChar != 47)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(311, 316);
                  break;
               case 99:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(99, 100);
                  break;
               case 100:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(101, 102);
                  break;
               case 101:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(101, 102);
                  break;
               case 102:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(317, 327);
                  break;
               case 103:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(104);
                  break;
               case 104:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(328, 333);
                  break;
               case 105:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(328, 333);
                  break;
               case 106:
                  if (curChar != 47)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(328, 333);
                  break;
               case 107:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(108);
                  break;
               case 108:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(334, 338);
                  break;
               case 109:
                  if (curChar == 45)
                     jjCheckNAddStates(334, 338);
                  break;
               case 110:
                  if (curChar == 47)
                     jjCheckNAddStates(334, 338);
                  break;
               case 111:
                  if (curChar == 40)
                     jjCheckNAdd(112);
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(112, 113);
                  break;
               case 113:
                  if (curChar != 41)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddTwoStates(99, 100);
                  break;
               case 114:
                  if (curChar == 45)
                     jjCheckNAddStates(339, 344);
                  break;
               case 115:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(345, 351);
                  break;
               case 116:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(117);
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(352, 356);
                  break;
               case 118:
                  if (curChar == 45)
                     jjCheckNAddStates(352, 356);
                  break;
               case 119:
                  if (curChar == 47)
                     jjCheckNAddStates(352, 356);
                  break;
               case 120:
                  if (curChar == 40)
                     jjCheckNAdd(121);
                  break;
               case 121:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(121, 113);
                  break;
               case 122:
                  if (curChar == 45)
                     jjCheckNAddStates(357, 362);
                  break;
               case 123:
                  if (curChar != 45)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(363, 369);
                  break;
               case 127:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(370, 380);
                  break;
               case 128:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(129);
                  break;
               case 129:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(381, 386);
                  break;
               case 130:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(381, 386);
                  break;
               case 131:
                  if (curChar != 47)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(381, 386);
                  break;
               case 132:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(132, 133);
                  break;
               case 133:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(134, 135);
                  break;
               case 134:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(134, 135);
                  break;
               case 135:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(387, 397);
                  break;
               case 136:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(137);
                  break;
               case 137:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(398, 403);
                  break;
               case 138:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(398, 403);
                  break;
               case 139:
                  if (curChar != 47)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(398, 403);
                  break;
               case 140:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(141);
                  break;
               case 141:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(404, 408);
                  break;
               case 142:
                  if (curChar == 45)
                     jjCheckNAddStates(404, 408);
                  break;
               case 143:
                  if (curChar == 47)
                     jjCheckNAddStates(404, 408);
                  break;
               case 144:
                  if (curChar == 40)
                     jjCheckNAdd(145);
                  break;
               case 145:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(145, 146);
                  break;
               case 146:
                  if (curChar != 41)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddTwoStates(132, 133);
                  break;
               case 147:
                  if (curChar == 45)
                     jjCheckNAddStates(409, 414);
                  break;
               case 148:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(415, 421);
                  break;
               case 149:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(150);
                  break;
               case 150:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(422, 426);
                  break;
               case 151:
                  if (curChar == 45)
                     jjCheckNAddStates(422, 426);
                  break;
               case 152:
                  if (curChar == 47)
                     jjCheckNAddStates(422, 426);
                  break;
               case 153:
                  if (curChar == 40)
                     jjCheckNAdd(154);
                  break;
               case 154:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(154, 146);
                  break;
               case 155:
                  if (curChar == 45)
                     jjCheckNAddStates(427, 432);
                  break;
               case 156:
                  if (curChar != 45)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(433, 439);
                  break;
               case 157:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 158:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(440, 450);
                  break;
               case 159:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(160);
                  break;
               case 160:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(451, 456);
                  break;
               case 161:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(451, 456);
                  break;
               case 162:
                  if (curChar != 47)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(451, 456);
                  break;
               case 163:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(163, 164);
                  break;
               case 164:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(165, 166);
                  break;
               case 165:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(165, 166);
                  break;
               case 166:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(457, 467);
                  break;
               case 167:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(168);
                  break;
               case 168:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(468, 473);
                  break;
               case 169:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(468, 473);
                  break;
               case 170:
                  if (curChar != 47)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(468, 473);
                  break;
               case 171:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(172);
                  break;
               case 172:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(474, 478);
                  break;
               case 173:
                  if (curChar == 45)
                     jjCheckNAddStates(474, 478);
                  break;
               case 174:
                  if (curChar == 47)
                     jjCheckNAddStates(474, 478);
                  break;
               case 175:
                  if (curChar == 40)
                     jjCheckNAdd(176);
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(176, 177);
                  break;
               case 177:
                  if (curChar != 41)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddTwoStates(163, 164);
                  break;
               case 178:
                  if (curChar == 45)
                     jjCheckNAddStates(479, 484);
                  break;
               case 179:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(485, 491);
                  break;
               case 180:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(181);
                  break;
               case 181:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(492, 496);
                  break;
               case 182:
                  if (curChar == 45)
                     jjCheckNAddStates(492, 496);
                  break;
               case 183:
                  if (curChar == 47)
                     jjCheckNAddStates(492, 496);
                  break;
               case 184:
                  if (curChar == 40)
                     jjCheckNAdd(185);
                  break;
               case 185:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(185, 177);
                  break;
               case 186:
                  if (curChar == 45)
                     jjCheckNAddStates(497, 502);
                  break;
               case 187:
                  if (curChar != 45)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(503, 509);
                  break;
               case 194:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 195:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(510, 520);
                  break;
               case 196:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(197);
                  break;
               case 197:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(521, 526);
                  break;
               case 198:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(521, 526);
                  break;
               case 199:
                  if (curChar != 47)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(521, 526);
                  break;
               case 200:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(200, 201);
                  break;
               case 201:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(202, 203);
                  break;
               case 202:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(202, 203);
                  break;
               case 203:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(527, 537);
                  break;
               case 204:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(205);
                  break;
               case 205:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(538, 543);
                  break;
               case 206:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(538, 543);
                  break;
               case 207:
                  if (curChar != 47)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(538, 543);
                  break;
               case 208:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(209);
                  break;
               case 209:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(544, 548);
                  break;
               case 210:
                  if (curChar == 45)
                     jjCheckNAddStates(544, 548);
                  break;
               case 211:
                  if (curChar == 47)
                     jjCheckNAddStates(544, 548);
                  break;
               case 212:
                  if (curChar == 40)
                     jjCheckNAdd(213);
                  break;
               case 213:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(213, 214);
                  break;
               case 214:
                  if (curChar != 41)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddTwoStates(200, 201);
                  break;
               case 215:
                  if (curChar == 45)
                     jjCheckNAddStates(549, 554);
                  break;
               case 216:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(555, 561);
                  break;
               case 217:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(218);
                  break;
               case 218:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(562, 566);
                  break;
               case 219:
                  if (curChar == 45)
                     jjCheckNAddStates(562, 566);
                  break;
               case 220:
                  if (curChar == 47)
                     jjCheckNAddStates(562, 566);
                  break;
               case 221:
                  if (curChar == 40)
                     jjCheckNAdd(222);
                  break;
               case 222:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(222, 214);
                  break;
               case 223:
                  if (curChar == 45)
                     jjCheckNAddStates(567, 572);
                  break;
               case 224:
                  if (curChar != 45)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(573, 579);
                  break;
               case 232:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(233, 234);
                  break;
               case 233:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAdd(233);
                  break;
               case 234:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(580, 583);
                  break;
               case 235:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(234);
                  break;
               case 236:
                  if (curChar != 46)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(237, 23);
                  break;
               case 237:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddTwoStates(237, 23);
                  break;
               case 238:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(584, 588);
                  break;
               case 239:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 3)
                     kind = 3;
                  jjCheckNAddStates(0, 4);
                  break;
               case 244:
                  if (curChar == 40)
                     jjCheckNAddStates(589, 593);
                  break;
               case 245:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddStates(589, 593);
                  break;
               case 246:
                  if (curChar == 46)
                     jjCheckNAdd(247);
                  break;
               case 247:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(594, 600);
                  break;
               case 249:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(250);
                  break;
               case 250:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(601, 606);
                  break;
               case 251:
                  if (curChar == 45)
                     jjCheckNAddStates(607, 612);
                  break;
               case 252:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(252, 253);
                  break;
               case 253:
                  if (curChar == 41 && kind > 24)
                     kind = 24;
                  break;
               case 254:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(255, 259);
                  break;
               case 255:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(613, 619);
                  break;
               case 256:
                  if (curChar == 46)
                     jjCheckNAddStates(620, 627);
                  break;
               case 257:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(628, 638);
                  break;
               case 258:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(639, 648);
                  break;
               case 259:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(607, 612);
                  break;
               case 260:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(649, 651);
                  break;
               case 261:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(652, 663);
                  break;
               case 262:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(664, 674);
                  break;
               case 265:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 276:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 281:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if (curChar == 45)
                     jjCheckNAddStates(675, 679);
                  break;
               case 283:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(284);
                  break;
               case 284:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(680, 684);
                  break;
               case 285:
                  if (curChar == 45)
                     jjCheckNAddStates(680, 684);
                  break;
               case 286:
                  if (curChar == 47)
                     jjCheckNAddStates(680, 684);
                  break;
               case 287:
                  if (curChar == 42)
                     jjCheckNAdd(288);
                  break;
               case 288:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAddStates(685, 687);
                  break;
               case 289:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(289, 290);
                  break;
               case 290:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(291, 292);
                  break;
               case 291:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(291, 292);
                  break;
               case 292:
                  if (curChar == 45)
                     jjCheckNAddStates(688, 692);
                  break;
               case 293:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(294);
                  break;
               case 294:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(693, 697);
                  break;
               case 295:
                  if (curChar == 45)
                     jjCheckNAddStates(693, 697);
                  break;
               case 296:
                  if (curChar == 47)
                     jjCheckNAddStates(693, 697);
                  break;
               case 297:
                  if (curChar == 42)
                     jjCheckNAdd(298);
                  break;
               case 298:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 30)
                     kind = 30;
                  jjCheckNAddStates(698, 700);
                  break;
               case 299:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 297;
                  break;
               case 300:
                  if (curChar == 45)
                     jjCheckNAddStates(701, 706);
                  break;
               case 301:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 287;
                  break;
               case 302:
                  if (curChar == 45)
                     jjCheckNAddStates(707, 712);
                  break;
               case 312:
                  if ((0x100000200L & l) != 0L)
                     jjAddStates(713, 714);
                  break;
               case 313:
                  if (curChar == 42)
                     jjCheckNAdd(314);
                  break;
               case 314:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(314, 315);
                  break;
               case 315:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(315, 316);
                  break;
               case 316:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(715, 720);
                  break;
               case 317:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(318);
                  break;
               case 318:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(721, 726);
                  break;
               case 319:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(721, 726);
                  break;
               case 320:
                  if (curChar != 47)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(721, 726);
                  break;
               case 321:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(321, 322);
                  break;
               case 322:
                  if (curChar == 44)
                     jjCheckNAddTwoStates(323, 324);
                  break;
               case 323:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(323, 324);
                  break;
               case 324:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(727, 732);
                  break;
               case 325:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(326);
                  break;
               case 326:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(733, 738);
                  break;
               case 327:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(733, 738);
                  break;
               case 328:
                  if (curChar != 47)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(733, 738);
                  break;
               case 329:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(739, 745);
                  break;
               case 330:
                  if (curChar != 45)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(746, 752);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x7ff81fe07ff81feL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 127;
                  else if ((0x7e0000004e00L & l) != 0L)
                     jjCheckNAdd(94);
                  else if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 125;
                  if (curChar == 99)
                     jjAddStates(753, 754);
                  else if (curChar == 114)
                     jjAddStates(755, 756);
                  else if (curChar == 105)
                     jjAddStates(757, 759);
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 230;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 192;
                  else if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 91;
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 81;
                  else if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 69;
                  else if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(12, 18);
                  break;
               case 3:
                  if ((0xf8000001f8000001L & l) != 0L)
                     jjCheckNAddStates(12, 18);
                  break;
               case 7:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(760, 761);
                  break;
               case 23:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(762, 763);
                  break;
               case 30:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(764, 765);
                  break;
               case 33:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(128, 133);
                  break;
               case 45:
               case 241:
                  if (curChar == 115)
                     jjCheckNAdd(26);
                  break;
               case 46:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 52:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(766, 767);
                  break;
               case 55:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(214, 219);
                  break;
               case 67:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 68:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if (curChar == 113)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 75:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(286, 290);
                  break;
               case 78:
                  if (curChar == 116)
                     jjCheckNAdd(71);
                  break;
               case 79:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 81:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 87:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(295, 299);
                  break;
               case 90:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 91:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 93:
                  if ((0x7e0000004e00L & l) != 0L)
                     jjCheckNAdd(94);
                  break;
               case 94:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(300, 310);
                  break;
               case 97:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(311, 316);
                  break;
               case 98:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(311, 316);
                  break;
               case 102:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(317, 327);
                  break;
               case 105:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(328, 333);
                  break;
               case 106:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(328, 333);
                  break;
               case 109:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(334, 338);
                  break;
               case 110:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(334, 338);
                  break;
               case 114:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(339, 344);
                  break;
               case 115:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(345, 351);
                  break;
               case 118:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(352, 356);
                  break;
               case 119:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(352, 356);
                  break;
               case 122:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(357, 362);
                  break;
               case 123:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(363, 369);
                  break;
               case 124:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 125:
                  if (curChar == 77)
                     jjCheckNAdd(94);
                  break;
               case 126:
                  if ((0x7ff81fe07ff81feL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 127;
                  break;
               case 127:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(370, 380);
                  break;
               case 130:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(381, 386);
                  break;
               case 131:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(381, 386);
                  break;
               case 135:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(387, 397);
                  break;
               case 138:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(398, 403);
                  break;
               case 139:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(398, 403);
                  break;
               case 142:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(404, 408);
                  break;
               case 143:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(404, 408);
                  break;
               case 147:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(409, 414);
                  break;
               case 148:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(415, 421);
                  break;
               case 151:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(422, 426);
                  break;
               case 152:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(422, 426);
                  break;
               case 155:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(427, 432);
                  break;
               case 156:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjCheckNAddStates(433, 439);
                  break;
               case 158:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(440, 450);
                  break;
               case 161:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(451, 456);
                  break;
               case 162:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(451, 456);
                  break;
               case 166:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(457, 467);
                  break;
               case 169:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(468, 473);
                  break;
               case 170:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(468, 473);
                  break;
               case 173:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(474, 478);
                  break;
               case 174:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(474, 478);
                  break;
               case 178:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(479, 484);
                  break;
               case 179:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(485, 491);
                  break;
               case 182:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(492, 496);
                  break;
               case 183:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(492, 496);
                  break;
               case 186:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(497, 502);
                  break;
               case 187:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 28)
                     kind = 28;
                  jjCheckNAddStates(503, 509);
                  break;
               case 188:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 189:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 190:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 189;
                  break;
               case 191:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 195:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(510, 520);
                  break;
               case 198:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(521, 526);
                  break;
               case 199:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(521, 526);
                  break;
               case 203:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(527, 537);
                  break;
               case 206:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(538, 543);
                  break;
               case 207:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(538, 543);
                  break;
               case 210:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(544, 548);
                  break;
               case 211:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(544, 548);
                  break;
               case 215:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(549, 554);
                  break;
               case 216:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(555, 561);
                  break;
               case 219:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(562, 566);
                  break;
               case 220:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(562, 566);
                  break;
               case 223:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(567, 572);
                  break;
               case 224:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 29)
                     kind = 29;
                  jjCheckNAddStates(573, 579);
                  break;
               case 225:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 226:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 240:
                  if (curChar == 105)
                     jjAddStates(757, 759);
                  break;
               case 242:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 248:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(768, 769);
                  break;
               case 251:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjAddStates(607, 612);
                  break;
               case 263:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 264:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 266:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 271:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 272:
                  if (curChar == 114)
                     jjAddStates(755, 756);
                  break;
               case 273:
                  if (curChar == 108)
                     jjCheckNAdd(71);
                  break;
               case 274:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 275:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 277:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 280:
                  if (curChar == 99)
                     jjAddStates(753, 754);
                  break;
               case 282:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(675, 679);
                  break;
               case 285:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(680, 684);
                  break;
               case 286:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(680, 684);
                  break;
               case 292:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(688, 692);
                  break;
               case 295:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(693, 697);
                  break;
               case 296:
                  if ((0x1000000010000000L & l) != 0L)
                     jjCheckNAddStates(693, 697);
                  break;
               case 300:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(701, 706);
                  break;
               case 302:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(707, 712);
                  break;
               case 303:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 304:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 303;
                  break;
               case 305:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 304;
                  break;
               case 306:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 305;
                  break;
               case 307:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 306;
                  break;
               case 308:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 307;
                  break;
               case 309:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 308;
                  break;
               case 310:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 309;
                  break;
               case 311:
                  if (curChar == 114)
                     jjAddStates(713, 714);
                  break;
               case 316:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(715, 720);
                  break;
               case 319:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(721, 726);
                  break;
               case 320:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(721, 726);
                  break;
               case 324:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(727, 732);
                  break;
               case 327:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(733, 738);
                  break;
               case 328:
                  if ((0x1000000010000000L & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(733, 738);
                  break;
               case 329:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(739, 745);
                  break;
               case 330:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 31)
                     kind = 31;
                  jjCheckNAddStates(746, 752);
                  break;
               case 331:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 311;
                  break;
               case 332:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 331;
                  break;
               case 333:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 332;
                  break;
               case 334:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 333;
                  break;
               case 335:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 334;
                  break;
               case 336:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 335;
                  break;
               case 337:
                  if (curChar == 104)
                     jjstateSet[jjnewStateCnt++] = 336;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(12, 18);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 338 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   233, 235, 236, 23, 238, 2, 3, 4, 5, 13, 17, 20, 2, 3, 4, 5, 
   10, 13, 17, 2, 3, 4, 5, 7, 10, 13, 19, 2, 3, 4, 5, 10, 
   11, 18, 12, 14, 9, 2, 3, 4, 7, 10, 15, 13, 16, 2, 3, 4, 
   5, 6, 7, 10, 13, 16, 2, 3, 4, 5, 7, 10, 13, 17, 16, 15, 
   13, 16, 2, 3, 4, 5, 7, 10, 13, 17, 15, 13, 16, 2, 3, 4, 
   5, 7, 10, 11, 18, 13, 17, 15, 13, 16, 2, 3, 4, 5, 7, 10, 
   13, 17, 19, 15, 13, 16, 2, 3, 4, 5, 10, 13, 17, 20, 27, 28, 
   33, 36, 40, 28, 30, 33, 34, 35, 36, 44, 28, 33, 34, 35, 42, 43, 
   28, 33, 34, 35, 36, 40, 30, 33, 34, 35, 38, 36, 39, 28, 29, 30, 
   33, 34, 35, 36, 39, 28, 30, 33, 34, 35, 36, 40, 39, 38, 36, 39, 
   28, 30, 33, 34, 35, 36, 40, 38, 36, 39, 37, 32, 41, 28, 30, 33, 
   34, 35, 36, 40, 42, 43, 38, 36, 39, 28, 30, 33, 34, 35, 36, 40, 
   44, 38, 36, 39, 49, 50, 55, 58, 62, 50, 52, 55, 56, 57, 58, 66, 
   50, 55, 56, 57, 64, 65, 50, 55, 56, 57, 58, 62, 52, 55, 56, 57, 
   60, 58, 61, 50, 51, 52, 55, 56, 57, 58, 61, 50, 52, 55, 56, 57, 
   58, 62, 61, 60, 58, 61, 50, 52, 55, 56, 57, 58, 62, 60, 58, 61, 
   59, 54, 63, 50, 52, 55, 56, 57, 58, 62, 64, 65, 60, 58, 61, 50, 
   52, 55, 56, 57, 58, 62, 66, 60, 58, 61, 72, 73, 74, 75, 73, 74, 
   75, 76, 77, 84, 85, 86, 87, 85, 86, 87, 88, 89, 95, 96, 98, 116, 
   117, 119, 120, 99, 100, 122, 123, 97, 95, 96, 98, 99, 100, 99, 100, 103, 
   104, 106, 107, 108, 110, 111, 114, 115, 99, 100, 105, 103, 104, 106, 109, 107, 
   108, 110, 111, 109, 107, 108, 110, 111, 114, 99, 100, 105, 103, 104, 106, 115, 
   118, 116, 117, 119, 120, 118, 116, 117, 119, 120, 122, 97, 95, 96, 98, 99, 
   100, 123, 128, 129, 131, 149, 150, 152, 153, 132, 133, 155, 156, 130, 128, 129, 
   131, 132, 133, 132, 133, 136, 137, 139, 140, 141, 143, 144, 147, 148, 132, 133, 
   138, 136, 137, 139, 142, 140, 141, 143, 144, 142, 140, 141, 143, 144, 147, 132, 
   133, 138, 136, 137, 139, 148, 151, 149, 150, 152, 153, 151, 149, 150, 152, 153, 
   155, 130, 128, 129, 131, 132, 133, 156, 159, 160, 162, 180, 181, 183, 184, 163, 
   164, 186, 187, 161, 159, 160, 162, 163, 164, 163, 164, 167, 168, 170, 171, 172, 
   174, 175, 178, 179, 163, 164, 169, 167, 168, 170, 173, 171, 172, 174, 175, 173, 
   171, 172, 174, 175, 178, 163, 164, 169, 167, 168, 170, 179, 182, 180, 181, 183, 
   184, 182, 180, 181, 183, 184, 186, 161, 159, 160, 162, 163, 164, 187, 196, 197, 
   199, 217, 218, 220, 221, 200, 201, 223, 224, 198, 196, 197, 199, 200, 201, 200, 
   201, 204, 205, 207, 208, 209, 211, 212, 215, 216, 200, 201, 206, 204, 205, 207, 
   210, 208, 209, 211, 212, 210, 208, 209, 211, 212, 215, 200, 201, 206, 204, 205, 
   207, 216, 219, 217, 218, 220, 221, 219, 217, 218, 220, 221, 223, 198, 196, 197, 
   199, 200, 201, 224, 235, 236, 23, 238, 235, 236, 237, 23, 238, 245, 246, 251, 
   254, 258, 246, 248, 251, 252, 253, 254, 262, 246, 251, 252, 253, 260, 261, 246, 
   251, 252, 253, 254, 258, 248, 251, 252, 253, 256, 254, 257, 246, 247, 248, 251, 
   252, 253, 254, 257, 246, 248, 251, 252, 253, 254, 258, 257, 256, 254, 257, 246, 
   248, 251, 252, 253, 254, 258, 256, 254, 257, 255, 250, 259, 246, 248, 251, 252, 
   253, 254, 258, 260, 261, 256, 254, 257, 246, 248, 251, 252, 253, 254, 258, 262, 
   256, 254, 257, 283, 284, 286, 301, 302, 285, 283, 284, 286, 301, 288, 289, 290, 
   293, 294, 296, 299, 300, 295, 293, 294, 296, 299, 289, 290, 298, 295, 293, 294, 
   296, 299, 300, 285, 283, 284, 286, 301, 302, 312, 313, 317, 318, 320, 321, 322, 
   330, 319, 317, 318, 320, 321, 322, 321, 322, 325, 326, 328, 329, 321, 322, 327, 
   325, 326, 328, 321, 322, 327, 325, 326, 328, 329, 319, 317, 318, 320, 321, 322, 
   330, 310, 337, 275, 279, 243, 264, 271, 8, 9, 24, 25, 31, 32, 53, 54, 
   249, 250, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, "\73", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0x1ffe06029L, 
};
static final long[] jjtoSkip = {
   0x6L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[338];
static private final int[] jjstateSet = new int[676];
static protected char curChar;
public FortranParserTokenManager(SimpleCharStream stream)
{
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}
public FortranParserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 338; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

public static Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2400L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
