/* Generated By:JavaCC: Do not edit this line. ParameterGUIParserConstants.java */
package Command.JavaCC;

public interface ParameterGUIParserConstants {

  int EOF = 0;
  int DIGIT = 3;
  int UNSIGNED_DIGIT = 4;
  int WHITESPACE = 5;
  int CHARACTER = 6;
  int RESERVED_CHAR = 7;
  int VAR_RESERVED_CHAR = 8;
  int EXPANSION_DELIMITER = 9;
  int VARIABLE_COMP = 10;
  int VARIABLE = 11;
  int STRING = 12;
  int COLON_PAIR = 13;
  int STEPPED_COLON_PAIR = 14;
  int FLOATING_POINT = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "<UNSIGNED_DIGIT>",
    "<WHITESPACE>",
    "<CHARACTER>",
    "<RESERVED_CHAR>",
    "<VAR_RESERVED_CHAR>",
    "\":\"",
    "<VARIABLE_COMP>",
    "<VARIABLE>",
    "<STRING>",
    "<COLON_PAIR>",
    "<STEPPED_COLON_PAIR>",
    "<FLOATING_POINT>",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
  };

}
