/* Generated By:JavaCC: Do not edit this line. FortranParserConstants.java */
package Command.JavaCC.Fortran;

public interface FortranParserConstants {

  int EOF = 0;
  int WHITESPACE = 3;
  int ONE_PLUS_WS = 4;
  int OPT_WS = 5;
  int UNSIGNED_DIGIT = 6;
  int DIGIT = 7;
  int CHARACTER = 8;
  int RESERVED_CHAR = 9;
  int VAR_RESERVED_CHAR = 10;
  int DIGICHAR = 11;
  int VARIABLE = 12;
  int ARRAY_VARIABLE = 13;
  int STRING = 14;
  int FLOATING_POINT = 15;
  int INT_IDENT = 16;
  int FLOAT_IDENT = 17;
  int MULTI_VARIABLE = 18;
  int CHAR_VARIABLE = 19;
  int MATH_INT_VAR = 20;
  int MATH_FLOAT_VAR = 21;
  int MATH_VAR = 22;
  int FORTRAN_ABS = 23;
  int FORTRAN_SQRT = 24;
  int FORTRAN_FLOAT_FUN = 25;
  int FORTRAN_TRUNC_FUN = 26;
  int FORTRAN_MOD_FUN = 27;
  int FORTRAN_INT = 28;
  int FORTRAN_REAL = 29;
  int FORTRAN_DOUBLE = 30;
  int FORTRAN_LOGICAL = 31;
  int FORTRAN_CHAR_1 = 32;
  int FORTRAN_CHAR_2 = 33;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "<WHITESPACE>",
    "<ONE_PLUS_WS>",
    "<OPT_WS>",
    "<UNSIGNED_DIGIT>",
    "<DIGIT>",
    "<CHARACTER>",
    "<RESERVED_CHAR>",
    "<VAR_RESERVED_CHAR>",
    "<DIGICHAR>",
    "<VARIABLE>",
    "<ARRAY_VARIABLE>",
    "<STRING>",
    "<FLOATING_POINT>",
    "<INT_IDENT>",
    "<FLOAT_IDENT>",
    "<MULTI_VARIABLE>",
    "<CHAR_VARIABLE>",
    "<MATH_INT_VAR>",
    "<MATH_FLOAT_VAR>",
    "<MATH_VAR>",
    "<FORTRAN_ABS>",
    "<FORTRAN_SQRT>",
    "<FORTRAN_FLOAT_FUN>",
    "<FORTRAN_TRUNC_FUN>",
    "<FORTRAN_MOD_FUN>",
    "<FORTRAN_INT>",
    "<FORTRAN_REAL>",
    "<FORTRAN_DOUBLE>",
    "<FORTRAN_LOGICAL>",
    "<FORTRAN_CHAR_1>",
    "<FORTRAN_CHAR_2>",
    "\";\"",
  };

}
