/* Generated By:JavaCC: Do not edit this line. FortranParserConstants.java */
package Command.JavaCC.Fortran;

public interface FortranParserConstants {

  int EOF = 0;
  int LINE_END = 1;
  int WHITESPACE = 2;
  int ONE_PLUS_WS = 3;
  int OPT_WS = 4;
  int UNSIGNED_DIGIT = 5;
  int DIGIT = 6;
  int CHARACTER = 7;
  int RESERVED_CHAR = 8;
  int VAR_RESERVED_CHAR = 9;
  int DIGICHAR = 10;
  int VARIABLE = 11;
  int ARRAY_VARIABLE = 12;
  int STRING = 13;
  int FLOATING_POINT = 14;
  int BOOL_CONSTANT = 15;
  int INT_IDENT = 16;
  int FLOAT_IDENT = 17;
  int MULTI_VARIABLE = 18;
  int CHAR_VARIABLE = 19;
  int MATH_INT_VAR = 20;
  int MATH_FLOAT_VAR = 21;
  int MATH_VAR = 22;
  int FORTRAN_ABS = 23;
  int FORTRAN_SQRT = 24;
  int FORTRAN_SIN = 25;
  int FORTRAN_ASIN = 26;
  int FORTRAN_COS = 27;
  int FORTRAN_ACOS = 28;
  int FORTRAN_TAN = 29;
  int FORTRAN_ATAN = 30;
  int FORTRAN_LOG = 31;
  int FORTRAN_EXP = 32;
  int FORTRAN_FLOAT_FUN = 33;
  int FORTRAN_TRUNC_FUN = 34;
  int FORTRAN_MOD_FUN = 35;
  int FORTRAN_FLOOR_FUN = 36;
  int FORTRAN_FRACTION_FUN = 37;
  int FORTRAN_INT = 38;
  int FORTRAN_REAL = 39;
  int FORTRAN_DOUBLE = 40;
  int FORTRAN_LOGICAL = 41;
  int FORTRAN_CHAR_1 = 42;
  int FORTRAN_CHAR_2 = 43;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<LINE_END>",
    "<WHITESPACE>",
    "<ONE_PLUS_WS>",
    "<OPT_WS>",
    "<UNSIGNED_DIGIT>",
    "<DIGIT>",
    "<CHARACTER>",
    "<RESERVED_CHAR>",
    "<VAR_RESERVED_CHAR>",
    "<DIGICHAR>",
    "<VARIABLE>",
    "<ARRAY_VARIABLE>",
    "<STRING>",
    "<FLOATING_POINT>",
    "<BOOL_CONSTANT>",
    "<INT_IDENT>",
    "<FLOAT_IDENT>",
    "<MULTI_VARIABLE>",
    "<CHAR_VARIABLE>",
    "<MATH_INT_VAR>",
    "<MATH_FLOAT_VAR>",
    "<MATH_VAR>",
    "<FORTRAN_ABS>",
    "<FORTRAN_SQRT>",
    "<FORTRAN_SIN>",
    "<FORTRAN_ASIN>",
    "<FORTRAN_COS>",
    "<FORTRAN_ACOS>",
    "<FORTRAN_TAN>",
    "<FORTRAN_ATAN>",
    "<FORTRAN_LOG>",
    "<FORTRAN_EXP>",
    "<FORTRAN_FLOAT_FUN>",
    "<FORTRAN_TRUNC_FUN>",
    "<FORTRAN_MOD_FUN>",
    "<FORTRAN_FLOOR_FUN>",
    "<FORTRAN_FRACTION_FUN>",
    "<FORTRAN_INT>",
    "<FORTRAN_REAL>",
    "<FORTRAN_DOUBLE>",
    "<FORTRAN_LOGICAL>",
    "<FORTRAN_CHAR_1>",
    "<FORTRAN_CHAR_2>",
  };

}
