#
# Makefile for /IPNShome/neffk/java/dev/doc/ @webproject5.pns.anl.gov
#
# publishes progress report
#

PROGRESS = /IPNShome/neffk/java/dev/isaw/IPNS_Software/SelectedGraphView/doc/IPNS_progress.text
DEST     = /IPNShome/neffk/www/html/argonne

all:
	echo "Publishing $(PROGRESS) --> $(DEST)"
	cp $(PROGRESS) $(DEST)
