#

default:
	@echo "Run 'make install' to update, build & install IPNS-GOV."

update:
	svn update
	# smartsvn.sh

install:
	mvn clean install
	# mvn deploy  (no longer deploy here, use Continuum... :-])

# redeploy:
	# mvn tomcat:deploy

