#

default:
	@echo "Run 'make install' to update, build & install IPNS-GOV."

update:
	svn update
	# smartsvn.sh

install:
	mvn clean install
	# mvn deploy  (no longer deploy, just install... :-])

# redeploy:
	# mvn tomcat:deploy

