//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.04 at 04:58:29 PM CDT 
//


package Web;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Web package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Findnexus_QNAME = new QName("", "findnexus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Web
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OneElement }
     * 
     */
    public OneElement createOneElement() {
        return new OneElement();
    }

    /**
     * Create an instance of {@link FindNexusResponse }
     * 
     */
    public FindNexusResponse createFindNexusResponse() {
        return new FindNexusResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindNexusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "findnexus")
    public JAXBElement<FindNexusResponse> createFindnexus(FindNexusResponse value) {
        return new JAXBElement<FindNexusResponse>(_Findnexus_QNAME, FindNexusResponse.class, null, value);
    }

}
